FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY performance/locustfile.py .

EXPOSE 8089

# Default command for master, can be overridden for worker
CMD ["locust", "-f", "locustfile.py"]
